// DO NOT MANUALLY EDIT THIS FILE
// This file was automatically generated by Specify
// Please use the app to update the values below
// Last updated: Wed Mar 04 2020

export const primaryBackgroundColor = "#000000";
export const primaryBorderColor = "#ffffff";
export const primaryTextColor = "#55ff55";
export const secondaryBackgroundColor = "#2a2a2a";
export const seconderyTextColor = "#d8d8d8";